### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dinhduynhat** [Zaseth/CPLiteServer#2]
![image](https://user-images.githubusercontent.com/20450856/28620329-a5e4219a-7236-11e7-8554-bdbc8d40c1c0.png)
when login and play game

**Comment by Zaseth** [comment]
You were the one adding me on Discord yeah. Did you fix the issue?

**Comment by dinhduynhat** [comment]
![image](https://user-images.githubusercontent.com/20450856/28661315-758b0db0-72e0-11e7-9872-01e5d6f54f47.png)
coin not working

**Comment by Zaseth** [comment]
**(P.S, I am not a wizard. So you can manually edit this mediaserver. Please use the Load.swf that is in /public/play/**
This means that you should edit the game files yourself.
